# Data Loading Demonstration

In [ ]:
%pip install pandas pyarrow tqdm

In [1]:
%load_ext autoreload
%autoreload 2
import warnings
warnings.filterwarnings("ignore", category=UserWarning)
import sys
sys.path.append('./lib')

## Loading Triage Malware Dataset

The dataset contains annotated TLS communication samples collected from a Triage-based malware sandbox environment.  
Each sample corresponds to network traffic generated during the execution of a malware specimen under controlled conditions.

The following columns represent the relevant semantic annotations used for analysis and modeling:

- **meta.application** — Application identifier. This field is not used in this dataset and is therefore set to `NA`.
- **meta.system** — Operating system metadata associated with the communication, typically indicating the OS family and version of the sandboxed environment.
- **meta.service** — Network-facing service or operating system subsystem derived from system metadata, enabling coarse-grained service-level classification.
- **meta.malware.family** — Malware family annotation. Samples without a confidently identified family are labeled as `NA`.
- **meta.host** — Host-level identifier or role. This field is not used in this dataset and is therefore set to `NA`.

Note that a single network connection may be annotated both with a malware family and a system service.  
In such cases, the connection is *triggered by the execution of the malware sample*, but the observed TLS communication corresponds to a **legitimate operating system service** (e.g., update checks, certificate validation, or telemetry) invoked by the malware rather than to a malware-specific network protocol.

## Load all data

In [2]:
from data_helper import get_families_frequency
import pyarrow.dataset as ds
import pyarrow.compute as pc

ds_malware = ds.dataset(f"../datasets/malware.parquet", format="parquet")


df_malware = ds_malware.to_table().to_pandas()
get_families_frequency(df_malware)

            count  count
0       44caliber    232
1    ades_stealer  19526
2      agenttesla   3006
3          amadey  45718
4         ardamax     70
..            ...    ...
110   xmrig_linux     34
111        xorist  19526
112          xred    615
113     xtremerat      1
114         xworm  44085

[115 rows x 2 columns]

## Loading per family
The dataset allows you to load only the columns you need, so you can collect information on available families without loading the entire dataset.
Then, the individual family datasets are loaded.

In [3]:
# Collect available familes:
families = (
    ds_malware
    .to_table(columns=["meta.malware.family"])
    .column("meta.malware.family")
    .unique()
    .to_pylist()
)
print(families)
# Load familes one by one:
for family in families:
    if family is not None:
        df_family = ds_malware.to_table(filter=(pc.field("meta.malware.family") == family)).to_pandas()
        print(f"{family} - {df_family.shape[0]} / {len(df_family)}")

[None, 'agenttesla', 'asyncrat', 'stormkitty', 'blackmoon', 'blihanstealer', 'cobaltstrike', 'floxif', 'gh0strat', 'lockbit', 'lumma', 'neconyd', 'purplefox', 'quasar', 'ramnit', 'redline', 'sectoprat', 'smokeloader', 'stealc', 'umbral', 'vidar', 'xmrig', 'xred', 'xworm', 'cosmu', 'gink', 'sparkrat', 'vipkeylogger', 'discordrat', 'blankgrabber', 'cryptolocker', 'formbook', 'sliver', 'guloader', 'remcos', 'masslogger', 'matiex', 'snakekeylogger', 'modiloader', 'amadey', 'koiloader', 'mimikatz', 'njrat', 'aurotun', 'wannacry', 'salatstealer', 'deerstealer', 'donutloader', 'socks5systemz', 'venomrat', 'rhadamanthys', 'neshta', 'nightingale', 'azorult', 'lokibot', 'rms', 'xenorat', 'metasploit', 'nanocore', 'gcleaner', 'hijackloader', 'berbew', 'warzonerat', 'revengerat', 'cyber_stealer', 'babylonrat', 'emotet', 'raccoon', 'ades_stealer', 'chaos', 'dcrat', 'dragonforce', 'jlocker', 'onlylogger', 'rokrat', 'xorist', 'trickbot', 'coffloader', 'raworld', 'sality', 'darkvision', 'xmrig_linux', 'xtremerat', 'ardamax', 'stealerium', 'glupteba', 'havoc', 'darkcomet', 'dharma', 'kinsing', 'kinsing_rootkit', 'darkcloud', 'destiny_stealer', 'pony', 'medusaransomware', 'crimsonrat', 'exelastealer', 'milleniumrat', 'xenarmor', 'seroxen', 'badrabbit', 'chimera', 'infinitylock', 'risepro', 'fickerstealer', 'hawkeye', 'oski', 'gandcrab', '44caliber', 'cerber', 'bdaejec', 'neptunerat', 'wshrat', 'meshagent', 'marsstealer', 'petya']
agenttesla - 3006 / 3006
asyncrat - 22046 / 22046
stormkitty - 5627 / 5627
blackmoon - 2026 / 2026
blihanstealer - 312 / 312
cobaltstrike - 20522 / 20522
floxif - 539 / 539
gh0strat - 20042 / 20042
lockbit - 19898 / 19898
lumma - 36695 / 36695
neconyd - 312 / 312
purplefox - 456 / 456
quasar - 14956 / 14956
ramnit - 320 / 320
redline - 20115 / 20115
sectoprat - 19898 / 19898
smokeloader - 463 / 463
stealc - 30688 / 30688
umbral - 20054 / 20054
vidar - 59983 / 59983
xmrig - 5594 / 5594
xred - 615 / 615
xworm - 44085 / 44085
cosmu - 126 / 126
gink - 273 / 273
sparkrat - 41 / 41
vipkeylogger - 20360 / 20360
discordrat - 22526 / 22526
blankgrabber - 532 / 532
cryptolocker - 531 / 531
formbook - 1923 / 1923
sliver - 50 / 50
guloader - 1797 / 1797
remcos - 9251 / 9251
masslogger - 20500 / 20500
matiex - 4 / 4
snakekeylogger - 39 / 39
modiloader - 20893 / 20893
amadey - 45718 / 45718
koiloader - 250 / 250
mimikatz - 542 / 542
njrat - 17805 / 17805
aurotun - 734 / 734
wannacry - 2907 / 2907
salatstealer - 4468 / 4468
deerstealer - 1336 / 1336
donutloader - 9598 / 9598
socks5systemz - 598 / 598
venomrat - 9212 / 9212
rhadamanthys - 31355 / 31355
neshta - 6891 / 6891
nightingale - 54 / 54
azorult - 561 / 561
lokibot - 406 / 406
rms - 350 / 350
xenorat - 176 / 176
metasploit - 1187 / 1187
nanocore - 9290 / 9290
gcleaner - 40782 / 40782
hijackloader - 1320 / 1320
berbew - 39 / 39
warzonerat - 13003 / 13003
revengerat - 964 / 964
cyber_stealer - 106 / 106
babylonrat - 60 / 60
emotet - 15 / 15
raccoon - 210 / 210
ades_stealer - 19526 / 19526
chaos - 19526 / 19526
dcrat - 19656 / 19656
dragonforce - 19526 / 19526
jlocker - 19526 / 19526
onlylogger - 10046 / 10046
rokrat - 19526 / 19526
xorist - 19526 / 19526
trickbot - 8 / 8
coffloader - 140 / 140
raworld - 16115 / 16115
sality - 74 / 74
darkvision - 1404 / 1404
xmrig_linux - 34 / 34
xtremerat - 1 / 1
ardamax - 70 / 70
stealerium - 106 / 106
glupteba - 4 / 4
havoc - 12 / 12
darkcomet - 905 / 905
dharma - 292 / 292
kinsing - 2 / 2
kinsing_rootkit - 1 / 1
darkcloud - 37 / 37
destiny_stealer - 694 / 694
pony - 254 / 254
medusaransomware - 10896 / 10896
crimsonrat - 260 / 260
exelastealer - 16 / 16
milleniumrat - 28 / 28
xenarmor - 100 / 100
seroxen - 3 / 3
badrabbit - 133 / 133
chimera - 133 / 133
infinitylock - 133 / 133
risepro - 137 / 137
fickerstealer - 130 / 130
hawkeye - 307 / 307
oski - 130 / 130
gandcrab - 410 / 410
44caliber - 232 / 232
cerber - 168 / 168
bdaejec - 14 / 14
neptunerat - 149 / 149
wshrat - 675 / 675
meshagent - 43 / 43
marsstealer - 14 / 14
petya - 14 / 14

It is possible to do more data analysis without reading the entire dataset using dataset. For instance, we can compute the count of samples for every malware family.

In [4]:
freq = (
    ds_malware
    .to_table(columns=["meta.malware.family"])
    .to_pandas()
    ["meta.malware.family"]
    .value_counts()
    .sort_index()
)
freq

meta.malware.family
44caliber         232
ades_stealer    19526
agenttesla       3006
amadey          45718
ardamax            70
                ...
xmrig_linux        34
xorist          19526
xred              615
xtremerat           1
xworm           44085
Name: count, Length: 115, dtype: int64

It is often best to load only the necessary columns and then filter or compute on the data frame.

In [6]:
_df = (
    ds_malware
    .to_table(columns=["meta.malware.family"])
    .to_pandas())
non_malware_samples = _df["meta.malware.family"].isna().sum()
print(f"Non malware samples={non_malware_samples}")

Non malware samples=576908

## Loading Windows Applications Dataset

The dataset contains annotated TLS communication samples collected from applications executed in a controlled Windows environment.  
Traffic was generated by legitimate Windows-based applications running inside **Windows Sandbox**, ensuring a clean and reproducible execution context.

The following columns represent the relevant semantic annotations used for analysis and modeling:

- **meta.application** — Application identifier in the normalized form `VENDOR.APPLICATION`, representing the originating software (e.g., `MICROSOFT.OUTLOOK`, `GOOGLE.CHROME`).
- **meta.system** — Operating system metadata associated with the communication, indicating the OS family and version of the sandboxed environment.
- **meta.service** — Network-facing service annotation. This field is not used in this dataset and is set to `NA`.
- **meta.malware** — Malware family annotation. This field is not used in this dataset and is set to `NA`.
- **meta.host** — Host-level identifier or role. This field is not used in this dataset and is set to `NA`.

The dataset includes only TLS connections directly attributable to the executed applications.  
Background operating system traffic and unrelated connections were explicitly filtered out to preserve a clean, application-centric view of network behavior.

In [9]:
from data_helper import get_applications_frequency
import pyarrow.dataset as ds
import pyarrow.compute as pc

dataset = ds.dataset(f"../datasets/winapps.parquet", format="parquet")
print("Loading dataset...")
df_applications = dataset.to_table().to_pandas()

get_applications_frequency(df_applications)

Loading dataset...

                                count  count
0                   Adamant.Messenger   2246
1                   AirDroid.AirDroid   3352
2   Apple.AppleApplicationSupport.x86     33
3                        Apple.iTunes     32
4                         Asana.Asana    463
..                                ...    ...
59                    agalwood.Motrix     32
60                deltachat.deltachat     32
61                  eMClient.eMClient    169
62               pCloudAG.pCloudDrive    171
63            qBittorrent.qBittorrent     32

[64 rows x 2 columns]