# Data Loading Demonstration

In [ ]:
%pip install pandas pyarrow tqdm

In [2]:
import sys
sys.path.append('./lib')

## Loading Triage Malware Dataset

The dataset contains annotated TLS communication samples collected from a Triage-based malware sandbox environment.  
Each sample corresponds to network traffic generated during the execution of a malware specimen under controlled conditions.

The following columns represent the relevant semantic annotations used for analysis and modeling:

- **meta.application** — Application identifier. This field is not used in this dataset and is therefore set to `NA`.
- **meta.system** — Operating system metadata associated with the communication, typically indicating the OS family and version of the sandboxed environment.
- **meta.service** — Network-facing service or operating system subsystem derived from system metadata, enabling coarse-grained service-level classification.
- **meta.malware** — Malware family annotation. Samples without a confidently identified family are labeled as `_none_`.
- **meta.host** — Host-level identifier or role. This field is not used in this dataset and is therefore set to `NA`.

Note that a single network connection may be annotated both with a malware family and a system service.  
In such cases, the connection is *triggered by the execution of the malware sample*, but the observed TLS communication corresponds to a **legitimate operating system service** (e.g., update checks, certificate validation, or telemetry) invoked by the malware rather than to a malware-specific network protocol.

In [3]:
import DatasetManager
malware_dataset = DatasetManager.MalwareDataset.load_from("../datasets/malware.parquet", 10000)
malware_dataset.dataframe

Reading Parquet files:   0%|          | 3/916 [00:01<07:59,  1.90it/s]

,sa,sp,da,dp,ps,pr,bs,br,ts,td,...,tls.ja3s,tls.ja4,tls.ja4s,tls.rec,meta.malware,meta.sample,meta.system,meta.application,meta.service,meta.host
0,10.127.0.189,49792.0,20.72.205.209,443.0,13,12,1262,8316,1.756762e+09,0.941528,...,2fe9b0e731d3d41b2b84e8e1d6186836,t12d1909h2_d83cc789557e_7af1ed941c26,t1204h2_c030_5333cdffa7d9,"[-211, 3753, -102, -1, -40, 1, 40, 64, -82, -2...",_none_,{'id': '250901-1aw26afr2z_behavioral1'},windows10-2004-x64,<NA>,windows10-2004-x64,<NA>
1,10.127.0.189,49801.0,40.126.31.67,443.0,64,54,49974,39987,1.756762e+09,128.561234,...,7d8fd34fdb13a7fff30d5a52846b6c4c,t12d1909h2_d83cc789557e_7af1ed941c26,t120400_c030_09f674154ab3,"[-226, 3954, -102, -1, -40, 1, 40, -445, -3616...",_none_,{'id': '250901-1aw26afr2z_behavioral1'},windows10-2004-x64,<NA>,windows10-2004-x64,<NA>
2,10.127.0.189,49803.0,40.126.31.67,443.0,48,40,35832,31235,1.756762e+09,138.264477,...,7d8fd34fdb13a7fff30d5a52846b6c4c,t12d1909h2_d83cc789557e_7af1ed941c26,t120400_c030_09f674154ab3,"[-226, 3954, -102, -1, -40, 1, 40, -469, -7637...",_none_,{'id': '250901-1aw26afr2z_behavioral1'},windows10-2004-x64,<NA>,windows10-2004-x64,<NA>
3,10.127.0.189,49804.0,20.72.205.209,443.0,14,14,4529,8280,1.756762e+09,1.195099,...,2fe9b0e731d3d41b2b84e8e1d6186836,t12d1909h2_d83cc789557e_7af1ed941c26,t1204h2_c030_5333cdffa7d9,"[-211, 3753, -102, -1, -40, 1, 40, 64, -82, -1...",_none_,{'id': '250901-1aw26afr2z_behavioral1'},windows10-2004-x64,<NA>,windows10-2004-x64,<NA>
4,10.127.0.189,49806.0,52.167.17.97,443.0,14,13,4035,4910,1.756762e+09,0.749950,...,2fe9b0e731d3d41b2b84e8e1d6186836,t12d1909h2_d83cc789557e_7af1ed941c26,t1204h2_c030_5333cdffa7d9,"[-211, 3753, -102, -1, -40, 1, 40, 64, -82, -1...",_none_,{'id': '250901-1aw26afr2z_behavioral1'},windows10-2004-x64,<NA>,windows10-2004-x64,<NA>
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2916,10.127.0.226,50533.0,150.171.27.11,443.0,30,36,5576,9750,1.756736e+09,99.549034,...,0f14538e1c9070becdad7739c67d6363,t13d1516h2_8daaf6152771_02713d6af862,t1206h2_c030_7136cef64a82,"[-2031, 5965, -102, -1, -40, -94, -446, -259, ...",_none_,{'id': '250901-rmzjdawrx2_behavioral1'},windows10-2004-x64,<NA>,windows10-2004-x64,<NA>
2917,10.127.0.226,50536.0,150.171.27.11,443.0,14,17,2980,7403,1.756736e+09,90.263329,...,0f14538e1c9070becdad7739c67d6363,t13d1516h2_8daaf6152771_02713d6af862,t1206h2_c030_7136cef64a82,"[-1755, 5965, -102, -1, -40, -94, -346, 286, 1...",_none_,{'id': '250901-rmzjdawrx2_behavioral1'},windows10-2004-x64,<NA>,windows10-2004-x64,<NA>
2918,10.127.0.226,50554.0,13.107.246.64,443.0,18,20,3586,9277,1.756736e+09,90.235289,...,15af977ce25de452b96affa2addb1036,t13d1516h2_8daaf6152771_02713d6af862,t130200_1302_a56c5b993250,"[-1771, 88, 1, -1, -579, 155, 36, 6425, 281, 6...",_none_,{'id': '250901-rmzjdawrx2_behavioral1'},windows10-2004-x64,<NA>,windows10-2004-x64,<NA>
2919,10.127.0.226,50715.0,13.107.246.65,443.0,17,19,5406,8991,1.756736e+09,45.351975,...,15af977ce25de452b96affa2addb1036,t13d1516h2_8daaf6152771_02713d6af862,t130200_1302_a56c5b993250,"[-1797, 88, 1, -1, -605, 155, 36, 6444, 281, 6...",_none_,{'id': '250901-rmzjdawrx2_behavioral1'},windows10-2004-x64,<NA>,windows10-2004-x64,<NA>
2920,10.127.0.226,50721.0,150.171.28.11,443.0,53,43,23981,17801,1.756736e+09,74.851634,...,0f14538e1c9070becdad7739c67d6363,t13d1516h2_8daaf6152771_02713d6af862,t1206h2_c030_7136cef64a82,"[-1755, 5965, -102, -1, -40, -94, -1292, -1184...",_none_,{'id': '250901-rmzjdawrx2_behavioral1'},windows10-2004-x64,<NA>,windows10-2004-x64,<NA>

In [ ]:
malware_dataset.summary()

## Loading Windows Applications Dataset

The dataset contains annotated TLS communication samples collected from applications executed in a controlled Windows environment.  
Traffic was generated by legitimate Windows-based applications running inside **Windows Sandbox**, ensuring a clean and reproducible execution context.

The following columns represent the relevant semantic annotations used for analysis and modeling:

- **meta.application** — Application identifier in the normalized form `VENDOR.APPLICATION`, representing the originating software (e.g., `MICROSOFT.OUTLOOK`, `GOOGLE.CHROME`).
- **meta.system** — Operating system metadata associated with the communication, indicating the OS family and version of the sandboxed environment.
- **meta.service** — Network-facing service annotation. This field is not used in this dataset and is set to `NA`.
- **meta.malware** — Malware family annotation. This field is not used in this dataset and is set to `NA`.
- **meta.host** — Host-level identifier or role. This field is not used in this dataset and is set to `NA`.

The dataset includes only TLS connections directly attributable to the executed applications.  
Background operating system traffic and unrelated connections were explicitly filtered out to preserve a clean, application-centric view of network behavior.

In [ ]:
import DatasetManager
winapps_dataset = DatasetManager.WinappsDataset.load_from("../datasets/winapps.parquet", 10000)
winapps_dataset.dataframe

In [ ]:
winapps_dataset.summary()

In [ ]:
winapps_dataset.get_application("Opera.Opera")

In [2]:
%load_ext autoreload
%autoreload 2

import sys
sys.path.append('./lib')
import DatasetManager as dm
m = dm.SohoDataset.load_from("../datasets/soho.parquet", "../datasets/soho.meta.parquet", 10000)
m.dataframe

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

Reading Parquet files:   3%|▎         | 3/104 [00:02<01:29,  1.13it/s]
Reading Parquet files: 100%|██████████| 104/104 [00:00<00:00, 448.43it/s]

,sa,sp,da,dp,ps,pr,bs,br,ts,td,...,tls.ja3s,tls.ja4,tls.ja4s,tls.rec,meta.sample,meta.system,meta.application,meta.service,meta.malware,meta.host
0,192.168.1.197,64925.0,20.189.173.9,443.0,15,12,4944,7574,1.758875e+09,3.010000,...,15af977ce25de452b96affa2addb1036,t13d1517h2_8daaf6152771_b6f405a00624,t130200_1302_a56c5b993250,"[-1926, 88, 1, -1, -766, 187, 6169, -69, -87, ...",{'src': 'raw_20250926082706'},macos,<NA>,<NA>,<NA>,<NA>
1,192.168.1.197,55301.0,17.248.209.74,443.0,17,16,4455,5770,1.758875e+09,1.673526,...,15af977ce25de452b96affa2addb1036,t13d2014h2_a09f3c656075_e42f34c56612,t130200_1302_a56c5b993250,"[-512, 122, 1, 36, 3233, 96, 69, -1, -69, -126...",{'src': 'raw_20250926082706'},macos,<NA>,<NA>,<NA>,<NA>
2,192.168.1.197,64929.0,35.186.234.31,443.0,8,5,2514,1098,1.758875e+09,60.970909,...,2b0648ab686ee45e0e7c35fcfb0eea7e,t13d1517h2_8daaf6152771_b6f405a00624,t130300_1301_6bbbaf601ed8,"[-2017, 128, 1, 68, -1, -53, 551, 57]",{'src': 'raw_20250926082706'},macos,<NA>,<NA>,<NA>,<NA>
3,192.168.1.128,59984.0,20.50.88.244,443.0,17,13,2942,7874,1.758875e+09,104.877683,...,15af977ce25de452b96affa2addb1036,t13d121100_a538d02d76d5_f6eeaf393d2e,t130200_1302_a56c5b993250,"[-296, 88, 1, -1, -361, 187, 6077, -69, 98, -5...",{'src': 'raw_20250926082706'},NaN,<NA>,<NA>,<NA>,<NA>
4,192.168.1.197,64931.0,140.82.113.25,443.0,13,12,3390,4897,1.758875e+09,2.720050,...,f4febc55ea12b31ae17cfb7e614afda8,t13d1516h1_8daaf6152771_0d365e64def3,t130200_1301_a56c5b993250,"[-1820, 122, 1, 42, 3151, 96, 53, -1, -53, 74,...",{'src': 'raw_20250926082706'},macos,<NA>,<NA>,<NA>,<NA>
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2437,192.168.1.197,52957.0,69.173.144.165,443.0,12,11,5100,6464,1.758887e+09,32.035127,...,067cb25c43ef022a6ff3439733f91661,t13d1516h2_8daaf6152771_d8a2da3f94cd,t1204h1_009d_ec53b3cc8a64,"[-1729, 72, 2983, 4, -262, -1, -40, 1, 40, -24...",{'src': 'raw_20250926113306'},windows,<NA>,<NA>,<NA>,<NA>
2438,192.168.1.197,52960.0,172.217.130.73,443.0,83,199,7319,389278,1.758887e+09,0.625133,...,eb1d94daa7e0344597e756a1fb6e7054,t13d1516h2_8daaf6152771_d8a2da3f94cd,t130200_1301_234ea6891581,"[-1796, 122, 1, 4487, -1, -53, -1121, 519, 724...",{'src': 'raw_20250926113306'},windows,<NA>,<NA>,<NA>,<NA>
2439,192.168.1.197,52961.0,172.217.130.73,443.0,71,193,7757,388965,1.758887e+09,0.788832,...,eb1d94daa7e0344597e756a1fb6e7054,t13d1516h2_8daaf6152771_d8a2da3f94cd,t130200_1301_234ea6891581,"[-1732, 122, 1, 4486, -1, -53, -1121, 519, 724...",{'src': 'raw_20250926113306'},windows,<NA>,<NA>,<NA>,<NA>
2440,192.168.1.197,52964.0,77.75.77.172,443.0,22,20,5217,7014,1.758887e+09,123.199135,...,eb1d94daa7e0344597e756a1fb6e7054,t13d1516h2_8daaf6152771_d8a2da3f94cd,t130200_1301_234ea6891581,"[-1716, 122, 1, 3470, -1, -53, -87, -1109, -20...",{'src': 'raw_20250926113306'},windows,<NA>,<NA>,<NA>,<NA>
2441,192.168.1.197,52965.0,77.75.77.172,443.0,7,6,3083,320,1.758887e+09,0.414592,...,None,t13d1516h2_8daaf6152771_d8a2da3f94cd,None,[-1716],{'src': 'raw_20250926113306'},windows,<NA>,<NA>,<NA>,<NA>

In [ ]:
{"id":"tcp.241","ts":1758877912.4912,"td":0.22640228271484,"ip":{"proto":"TCP","src":"192.168.1.149","dst":"54.247.24.75","bsent":539,"brecv":444,"psent":6,"precv":4},"tcp":{"srcport":33708,"dstport":80,"segs":[{"ts":1758877912.4912,"dir":-1,"len":0,"flags":{"str":"uaprSf","val":2}},{"ts":1758877912.5517,"dir":1,"len":0,"flags":{"str":"uAprSf","val":18}},{"ts":1758877912.5526,"dir":-1,"len":0,"flags":{"str":"uAprsf","val":16}},{"ts":1758877912.5538,"dir":-1,"len":219,"flags":{"str":"uAPrsf","val":24}},{"ts":1758877912.6077,"dir":1,"len":0,"flags":{"str":"uAprsf","val":16}},{"ts":1758877912.6217,"dir":1,"len":228,"flags":{"str":"uAPrsf","val":24}},{"ts":1758877912.6227,"dir":-1,"len":0,"flags":{"str":"uAprsf","val":16}},{"ts":1758877912.6668,"dir":-1,"len":0,"flags":{"str":"uAprsF","val":17}},{"ts":1758877912.7167,"dir":1,"len":0,"flags":{"str":"uAprsF","val":17}},{"ts":1758877912.7176,"dir":-1,"len":0,"flags":{"str":"uAprsf","val":16}}]},"http":{"req":[{"method":"GET","uri":"http://dac-api-prod.tpv-analytics.com/prod/v1/time/","agent":"Dalvik/2.1.0 (Linux; U; Android 11; 2021/22 Philips UHD Android TV Build/RTT2.211108.001)","rnum":29091}],"res":[{"code":"200","content_type":"text/html; charset=utf-8","content_len":"2","rnum":29091}]},"meta":{"sample":{"src":"raw_20250926090304"},"system":{"os":""}}}