## 1. Dataset Sanity & Coverage Checks

* Number of connections per application (long-tail detection)
* Temporal coverage per application (days/weeks active)
* Missingness analysis per feature (global + per-app)
* Cardinality of categorical fields (SNI, ALPN, cipher suite, TLS version)
* Fraction of resumed sessions vs full handshakes

In [6]:
%load_ext autoreload
%autoreload 2
import warnings
warnings.filterwarnings("ignore", category=UserWarning)
import sys
sys.path.append('../lib')

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [7]:
import pyarrow.dataset as ds
import pyarrow.compute as pc


dataset = ds.dataset(f"../../datasets/winapps.parquet", format="parquet")
print("Loading dataset...")
df_applications = dataset.to_table().to_pandas()

Loading dataset...

In [8]:
from data_helper import get_applications_frequency, temporal_coverage_per_application
df_connections_per_application = get_applications_frequency(df_applications)
df_temporal_coverage_per_application = temporal_coverage_per_application(df_applications)

In [9]:
df_connections_per_application

                                count  count
0                   Adamant.Messenger   3613
1                   AirDroid.AirDroid   5707
2   Apple.AppleApplicationSupport.x86     33
3                        Apple.iCloud   1414
4                        Apple.iTunes   2144
..                                ...    ...
62                    agalwood.Motrix   1459
63                deltachat.deltachat     32
64                  eMClient.eMClient   3364
65               pCloudAG.pCloudDrive   2209
66            qBittorrent.qBittorrent   1285

[67 rows x 2 columns]

In [10]:
df_temporal_coverage_per_application

                  application        day  samples
0           Adamant.Messenger 2024-07-16       35
1           Adamant.Messenger 2024-07-17       34
2           Adamant.Messenger 2024-07-18       33
3           Adamant.Messenger 2024-07-19       34
4           Adamant.Messenger 2024-07-20       33
...                       ...        ...      ...
4094  qBittorrent.qBittorrent 2025-02-24       63
4095  qBittorrent.qBittorrent 2025-02-25       83
4096  qBittorrent.qBittorrent 2025-02-26       50
4097  qBittorrent.qBittorrent 2025-02-27       76
4098  qBittorrent.qBittorrent 2025-02-28       82

[4099 rows x 3 columns]